### ISSUE TITLE
Certificate?

### ISSUE THREAD

**Issue by johnwargo** [fhessel/esp32_https_server_compat#2]
Where does this library get the certificate to use for TLS?  I don't see anything in the instructions or sample that uses one.

**Comment by johnwargo** [comment]
I cloned your https://github.com/fhessel/esp32_https_server project and ran the script to generate the certs then copied them to my project.  but when I initialize the server, I get the following output to the monitor:

```text
setupCert failed
```

**Comment by fhessel** [comment]
I added a variant of the HelloServer example: [HelloServerSecure](https://github.com/fhessel/esp32_https_server_compat/blob/3c3fe8479af06cc06e8db643acc81501217427bb/examples/HelloServerSecure/HelloServerSecure.ino). It basically shows how you can add certificate header files as they are used in the examples of [esp32_https_server](https://github.com/fhessel/esp32_https_server).

The [create_cert.sh](https://github.com/fhessel/esp32_https_server/blob/master/extras/create_cert.sh) in that repo shows how you can create a minimal CA and a server certificate and convert them into a header file in DER format, but depending on where you get your certificate from, you might another chain of openssl calls. You'll find most of them by doing a web search, but if you have a particular setup, feel free to ping me back with what you've got and we'll see how to make it work with the server.
