### ISSUE TITLE
Raw Post-Data not handled

### ISSUE THREAD

**Issue by jakobklein** [fhessel/esp32_https_server_compat#3]
When I send a POST-Body that is neither  form-data nor x-www-formurlencoded but just raw data, `server.args(); ` returns 0 and I cannot access the data.
Example: `{
    "name": "foo"
}`
or 
`curl --location --request POST 'https://192.168.178.32/echo' --header 'Content-Type: application/json' --data-raw '{
    "name": "foo"
}'`
WebServer.h got me the raw data by calling server.arg(0)

**Comment by fhessel** [comment]
Did you try to [call it this way](https://github.com/fhessel/esp32_https_server_compat/blob/3c3fe8479af06cc06e8db643acc81501217427bb/src/ESPWebServer.cpp#L198)?

```c++
String body = server.arg("plain");
```

I briefly tested it and that worked for me, but I see that this could be more intuitive or at least be documented better.

**Comment by jakobklein** [comment]
Yes, this works! Thx for pointing me there.
