### ISSUE TITLE
C:\RH\Sources\RH\RemoteHomeArduinoSketches\WiFi_ESP32\libraries\esp32_https_server_compat\src\ESPWebServer.cpp:3:39: fatal error: HTTPMultipartBodyParser.hpp: No such file or directory

### ISSUE THREAD

**Issue by robertgregor** [fhessel/esp32_https_server_compat#4]
Hi seems, that I have a problem to compile it.

C:\RH\Sources\RH\RemoteHomeArduinoSketches\WiFi_ESP32\libraries\esp32_https_server_compat\src\ESPWebServer.cpp:3:39: fatal error: HTTPMultipartBodyParser.hpp: No such file or directory

Robert

**Comment by fhessel** [comment]
Do you have the underlying library _ESP32 HTTPS Server_ (without the "compat") installed? This library is just a thin layer on top of the other, which makes it more compatible with the existing WebServer interface. Depending on how you installed this library, the Arduino IDE may not automatically download the other library.

Please check the following:

- Go to _Sketch_ → _Include Library_ → _Manage Libraries..._
- Search for `esp32_https_server`
- You should see two libraries in the list: _ESP32 HTTPS Server_ and *esp32_https_server_compat*, and **both** have to be installed. For the _ESP32 HTTPS Server_, it has to be version 1.0.0.
- If not, install the missing library.

If that doesn't help, please let me know.

**Comment by robertgregor** [comment]
I see, thanks for the answer. Interesting, but you are probably right. Yes, I have of course your esp32 https server, but I have it in the libraries folder, which is on the same level as the sketches. This normally loads the other libraries correctly, but probably not in the case of HTTPServer.hpp...

**Comment by robertgregor** [comment]
OK, I have included
#include <ESPWebServer.hpp>

And did ESPWebServer server;

But seems, it is not fully compatible with the original WebServer i.e. I have error here:

Sensor:278:37: error: 'class ESPWebServer' has no member named 'client'

       WiFiClient client = rh.server.client();    

                                     ^

C:\RH\Sources\RH\RemoteHomeArduinoSketches\WiFi_ESP32\Sensor\Sensor.ino: In lambda function:

Sensor:296:70: error: 'DIGEST_AUTH' was not declared in this scope

       if (rh.verifyUser(usr)) return rh.server.requestAuthentication(DIGEST_AUTH, rh.www_realm, rh.authFailResponse);

**Comment by fhessel** [comment]
Digest-based authentication [is not implemented](https://github.com/fhessel/esp32_https_server_compat#state-of-development) as it's also missing in the underlying library.

The `client()` function is not implemented, indeed. The main issue with that is that `esp32_https_server` does not make use of `WiFiClient` but talks directly to the FreeRTOS network stack (we need to do that to handle connection and TLS state better). I'm not sure if I'm able to construct a `WiFiClient` from there. So this library is still no (and most likely will never be) 100%-drop-in-replacement but a way to make it easier to switch between both web server implementations.

But maybe one can address this from a functional point of view: What is your goal with getting the `WiFiClient`? Do you need the client's address?

**Comment by robertgregor** [comment]
Hi, my goal was to use your lirary together with the ESP camera library, which use WiFiClient...

**Comment by robertgregor** [comment]
Thanks for the feedback anyway...

**Comment by robertgregor** [comment]
Thanks
